# Generated by Django 3.1.7 on 2021-05-02 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210502_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
