# Generated by Django 3.1.7 on 2021-05-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist_created_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('listing', 'author')},
        ),
    ]
